### PR TITLE
Add generate_docs to CI

### PR DESCRIPTION
**Pull request by benjaminoakes**
I've only been testing this manually, but it's pretty important to make sure it's working.

### CODE REVIEW

**Comment by zefta** [comment]
👍

**Comment by kstevens715** [comment]
So it runs this on Travis? I didn't look at this very deep, but how does it get access to the WebAdMIT code base on Travis?

**Comment by benjaminoakes** [comment]
> So it runs this on Travis?

Yup.  It's public.  [Here's an example of it building the site and checking that all the links are good.](https://travis-ci.org/Liaison-Intl/Liaison-Intl.github.io/builds/152476834)

> but how does it get access to the WebAdMIT code base on Travis?

It doesn't.  It just uses the cached schemata that are already in the repo.  We have them there for reference purposes, largely because I know there is tooling to generate API clients that someone could potentially use...  In any case it's all the same information as found on the website.

**Comment by benjaminoakes** [comment]
I'm thinking I'll go ahead and merge this, since it's just a CI change mostly for @zefta if he needs to update the site.

**Pull request merged**
